version: '3.9'

services:
  app:
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - JWT_KEY=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=ffd061158@gmail.com
      - SPRING_MAIL_PASSWORD=tzfapruacoytinww
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - POSTGRES_USERNAME=someuser
      - POSTGRES_PASSWORD=somepass
      - POSTGRES_URL=jdbc:postgresql://db:5432/publishing
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_DB=publishing
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=somepass
      - PGDATA=/data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    expose:
      - '5432'
    restart: unless-stopped