services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: publishing
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: somepass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432