server:
  port: 8080
spring:
  application:
    name: publishing
  datasource:
    url: jdbc:postgresql://localhost:5432/publishing
    username: someuser
    password: somepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.index.html

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health

  endpoint:
    health:
      show-details: always