server:
  port: 8080

token:
  key: ${JWT_KEY}
  lifetime: 1_800_000

spring:
  application:
    name: publishing
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    locations: classpath:migrations
    url: ${POSTGRES_URL}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    enabled: true
    path: /index.html