create table if not exists customers
(
    is_deleted boolean not null,
    id         bigint generated by default as identity
        primary key,
    email      varchar(255)
        unique,
    name       varchar(255),
    phone      varchar(255)
);

alter table customers
    owner to someuser;

create table if not exists formats
(
    is_deleted  boolean      not null,
    id          bigint generated by default as identity
        primary key,
    designation varchar(255),
    title       varchar(255) not null
        unique
);

alter table formats
    owner to someuser;

create table if not exists profile
(
    birthday   date,
    started_at date,
    id         bigint generated by default as identity
        primary key,
    user_id    bigint
        unique,
    address    varchar(255),
    phone      varchar(255)
        unique
);

alter table profile
    owner to someuser;

create table if not exists types
(
    is_deleted boolean      not null,
    id         bigint generated by default as identity
        primary key,
    title      varchar(255) not null
        unique
);

alter table types
    owner to someuser;

create table if not exists books
(
    is_deleted     boolean      not null,
    book_format_id bigint
        constraint fkmt1q886k0q5wogevbcpwrgh1m
            references formats,
    book_type_id   bigint
        constraint fkcwv1mx9pqvh6gg5743u91ga2k
            references types,
    id             bigint generated by default as identity
        primary key,
    order_id       bigint
        unique,
    title          varchar(255) not null,
    authors        varchar(255)[]
);

alter table books
    owner to someuser;

create table if not exists files
(
    workable   boolean not null,
    book_id    bigint
        constraint fke4x0y3cbmqqms7ldubhj5qe7g
            references books,
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    path       varchar(255)
);

alter table files
    owner to someuser;

create table if not exists books_files
(
    book_id  bigint not null
        constraint fk9y6t6m84rmllwecqhm9qt593c
            references books,
    files_id bigint not null
        unique
        constraint fktrgk2dpylduwvpm5jh3xomany
            references files
);

alter table books_files
    owner to someuser;

create table if not exists formats_books
(
    book_format_id bigint not null
        constraint fkanllum2j3fndaa259lvxelfsj
            references formats,
    books_id       bigint not null
        unique
        constraint fkcu8v36ubjaw0rdkqkpy63te56
            references books
);

alter table formats_books
    owner to someuser;

create table if not exists orders
(
    is_deleted  boolean not null,
    number      integer,
    book_id     bigint
        unique
        constraint fki0uonhq5m6jxxlt5smyobjrdv
            references books,
    created_at  timestamp(6),
    customer_id bigint  not null
        constraint fkpxtb8awmi0dk6smoh2vp1litg
            references customers,
    finished_at timestamp(6),
    id          bigint generated by default as identity
        primary key,
    updated_at  timestamp(6),
    comment     varchar(255),
    deadline    varchar(255),
    status      varchar(255)
        constraint orders_status_check
            check ((status)::text = ANY
                   ((ARRAY ['AWAIT'::character varying, 'IN_WORK'::character varying, 'COMPLETED'::character varying])::text[]))
);

alter table orders
    owner to someuser;

alter table books
    add constraint fkl10e1j3e6o5wsckd3h55ordj
        foreign key (order_id) references orders;

create table if not exists customers_orders
(
    customer_id bigint not null
        constraint fk23d13l73po2yhpnru16evw5o3
            references customers,
    orders_id   bigint not null
        unique
        constraint fkcgubpw142krbvsbpfumpss2wl
            references orders
);

alter table customers_orders
    owner to someuser;

create table if not exists types_books
(
    book_type_id bigint not null
        constraint fkskhwmf1fu9ice7e3gotdur7qf
            references types,
    books_id     bigint not null
        unique
        constraint fkr5osdh4d2w7eusabbtr2tuaeq
            references books
);

alter table types_books
    owner to someuser;

create table if not exists users
(
    is_deleted boolean not null,
    id         bigint generated by default as identity
        primary key,
    profile_id bigint
        unique
        constraint fk5q3e9303ap1wvtia6sft7ht1s
            references profile,
    email      varchar(255)
        unique,
    password   varchar(255),
    position   varchar(255)
        constraint users_position_check
            check (("position")::text = ANY
                   ((ARRAY ['EDITOR'::character varying, 'IMPOSER'::character varying])::text[])),
    role       varchar(255)
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['ROLE_USER'::character varying, 'ROLE_MODERATOR'::character varying, 'ROLE_ADMIN'::character varying])::text[])),
    username   varchar(255)
);

alter table users
    owner to someuser;

alter table profile
    add constraint fks14jvsf9tqrcnly0afsv0ngwv
        foreign key (user_id) references users;

create table if not exists user_tasks
(
    is_deleted  boolean not null,
    created_at  timestamp(6),
    finished_at timestamp(6),
    id          bigint generated by default as identity
        primary key,
    order_id    bigint  not null
        constraint fkd9b9h9cc53nisfv3lm4mqgor5
            references orders,
    updated_at  timestamp(6),
    user_id     bigint  not null
        constraint fksrpyfa9asu2ymkcqr7jol85o2
            references users,
    status      varchar(255)
        constraint user_tasks_status_check
            check ((status)::text = ANY
                   ((ARRAY ['AWAIT'::character varying, 'IN_WORK'::character varying, 'COMPLETED'::character varying])::text[])),
    title       varchar(255)
);

alter table user_tasks
    owner to someuser;

create table if not exists orders_tasks
(
    order_id bigint not null
        constraint fka18lcprdj7a8n5fwaqgidp95x
            references orders,
    tasks_id bigint not null
        unique
        constraint fkffab0945tffom1ricc6uiyxay
            references user_tasks
);

alter table orders_tasks
    owner to someuser;

create table if not exists users_tasks
(
    tasks_id bigint not null
        unique
        constraint fkqrnj55uvmbxsu8xylpj0kxqaa
            references user_tasks,
    user_id  bigint not null
        constraint fk6frwjo48hefay0rg31q970r8t
            references users
);

alter table users_tasks
    owner to someuser;


ALTER SEQUENCE customers_id_seq RESTART WITH 1;
ALTER SEQUENCE formats_id_seq RESTART WITH 1;
ALTER SEQUENCE types_id_seq RESTART WITH 1;
ALTER SEQUENCE profile_id_seq RESTART WITH 1;
ALTER SEQUENCE orders_id_seq RESTART WITH 1;
ALTER SEQUENCE files_id_seq RESTART WITH 1;
ALTER SEQUENCE books_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;
ALTER SEQUENCE user_tasks_id_seq RESTART WITH 1;